SELECT * from Department
-- EXEC PR_DEPT_INSERT 'Cardiology','Heart-related treatments and services',1,2;

CREATE PROCEDURE PR_DEPT_INSERT

    @DEPARTMENTNAME     NVARCHAR(100),
    @DESCRIPTION        NVARCHAR(250),
    @ISACTIVE           BIT,
    @USERID             INT

AS
BEGIN

    INSERT INTO DEPARTMENT VALUES (
        @DEPARTMENTNAME,
        @DESCRIPTION,
        @ISACTIVE,
        GETDATE(),
        GETDATE(),
        @USERID
    );

END;

-- EXEC PR_DEPT_UPDATEBYPK 1,'Cardiology','Heart-related treatments and services',0,2;

CREATE PROCEDURE PR_DEPT_UPDATEBYPK

    @DEPARTMENTID       INT,
    @DEPARTMENTNAME     NVARCHAR(100),
    @DESCRIPTION        NVARCHAR(250),
    @ISACTIVE           BIT,
    @USERID             INT

AS
BEGIN
    UPDATE DEPARTMENT
    SET 
        DEPARTMENTNAME = @DEPARTMENTNAME,
        [DESCRIPTION] = @DESCRIPTION,
        ISACTIVE = @ISACTIVE,
        MODIFIED = GETDATE(),
        USERID = @USERID

    WHERE DEPARTMENTID = @DEPARTMENTID;

END;

-- EXEC PR_DEPT_DELETEBYPK 1

CREATE PROCEDURE PR_DEPT_DELETEBYPK

    @DEPARTMENTID       INT

AS
BEGIN
    DELETE
    FROM DEPARTMENT
    WHERE DEPARTMENTID = @DEPARTMENTID;
END;

--EXEC PR_DEPT_SELECTBYPK 1

CREATE PROCEDURE PR_DEPT_SELECTBYPK

    @DEPARTMENTID       INT

AS
BEGIN
    SELECT 
        DEPARTMENTID,
        DEPARTMENTNAME,
        [DESCRIPTION],
        ISACTIVE,
        CREATED,
        MODIFIED,
        USERID

    FROM DEPARTMENT
    WHERE DEPARTMENTID = @DEPARTMENTID;
END;


-- EXEC PR_DEPT_SELECTALL

CREATE PROCEDURE PR_DEPT_SELECTALL

AS
BEGIN
    SELECT 
        DEPARTMENT.DEPARTMENTID,
        DEPARTMENT.DEPARTMENTNAME,
        DEPARTMENT.[DESCRIPTION],
        DEPARTMENT.ISACTIVE,
        DEPARTMENT.CREATED,
        DEPARTMENT.MODIFIED,
        [USER].USERNAME,
        DEPARTMENT.USERID

    FROM DEPARTMENT D INNER JOIN [USER] U ON U.USERID = D.USERID;

END;

