-- EXEC PR_DOCTORDEPARTMENT_INSERT 

CREATE PROCEDURE PR_DOCTORDEPARTMENT_INSERT

    @DOCTORID       INT,
    @DEPARTMENTID   INT,
    @USERID         INT

AS
BEGIN

    INSERT INTO DOCTORDEPARTMENT
    VALUES (
        @DOCTORID,
        @DEPARTMENTID,
        GETDATE(),
        GETDATE(),
        @USERID
    );

END;


-- EXEC PR_DOCTORDEPARTMENT_UPDATEBYPK

CREATE PROCEDURE PR_DOCTORDEPARTMENT_UPDATEBYPK

    @DOCTORDEPARTMENTID    INT,
    @DOCTORID              INT,
    @DEPARTMENTID          INT,
    @USERID                INT

AS
BEGIN

    UPDATE DOCTORDEPARTMENT
    SET 
        DOCTORID     = @DOCTORID,
        DEPARTMENTID = @DEPARTMENTID,
        MODIFIED     = GETDATE(),
        USERID       = @USERID

    WHERE DOCTORDEPARTMENTID = @DOCTORDEPARTMENTID;

END;


-- EXEC PR_DOCTORDEPARTMENT_DELETEBYPK

CREATE PROCEDURE PR_DOCTORDEPARTMENT_DELETEBYPK

    @DOCTORDEPARTMENTID    INT

AS
BEGIN

    DELETE FROM DOCTORDEPARTMENT
    WHERE DOCTORDEPARTMENTID = @DOCTORDEPARTMENTID;

END;


-- EXEC PR_DOCTORDEPARTMENT_SELECTBYID 1

CREATE PROCEDURE PR_DOCTORDEPARTMENT_SELECTBYID

    @DOCTORDEPARTMENTID    INT

AS
BEGIN

    SELECT 
        DOCTORDEPARTMENTID,
        DOCTORID,
        DEPARTMENTID,
        CREATED,
        MODIFIED,
        USERID

    FROM DOCTORDEPARTMENT
    WHERE DOCTORDEPARTMENTID = @DOCTORDEPARTMENTID;

END;


-- EXEC PR_DOCTORDEPARTMENT_SELECTALL

CREATE PROCEDURE PR_DOCTORDEPARTMENT_SELECTALL

AS
BEGIN

    SELECT 
        DD.DOCTORDEPARTMENTID,
        DD.DOCTORID,
        D.NAME AS DOCTORNAME,
        DD.DEPARTMENTID,
        DP.DEPARTMENTNAME,
        DD.CREATED,
        DD.MODIFIED,
        DD.USERID,
        U.USERNAME
    FROM DOCTORDEPARTMENT DD
    INNER JOIN DOCTOR D ON D.DOCTORID = DD.DOCTORID
    INNER JOIN DEPARTMENT DP ON DP.DEPARTMENTID = DD.DEPARTMENTID
    INNER JOIN [USER] U ON U.USERID = DD.USERID;

END;
